#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean libso phaseChangeTwoPhaseMixturesNuc
wclean
wclean interPhaseChangeDyMFoam

#------------------------------------------------------------------------------
